//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.SR1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="SR1.BanqueService")]
    public interface BanqueService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/listCompteRequest", ReplyAction="http://ws/BanqueService/listCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.SR1.listCompteResponse listCompte(ConsoleApp1.SR1.listCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/listCompteRequest", ReplyAction="http://ws/BanqueService/listCompteResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SR1.listCompteResponse> listCompteAsync(ConsoleApp1.SR1.listCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getCompteRequest", ReplyAction="http://ws/BanqueService/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.SR1.getCompteResponse getCompte(ConsoleApp1.SR1.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getCompteRequest", ReplyAction="http://ws/BanqueService/getCompteResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SR1.getCompteResponse> getCompteAsync(ConsoleApp1.SR1.getCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/ConversionEruoToDHRequest", ReplyAction="http://ws/BanqueService/ConversionEruoToDHResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.SR1.ConversionEruoToDHResponse ConversionEruoToDH(ConsoleApp1.SR1.ConversionEruoToDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/ConversionEruoToDHRequest", ReplyAction="http://ws/BanqueService/ConversionEruoToDHResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.SR1.ConversionEruoToDHResponse> ConversionEruoToDHAsync(ConsoleApp1.SR1.ConversionEruoToDHRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listCompte", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listCompteRequest {
        
        public listCompteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listCompteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class listCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApp1.SR1.compte[] @return;
        
        public listCompteResponse() {
        }
        
        public listCompteResponse(ConsoleApp1.SR1.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long code;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(long code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApp1.SR1.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(ConsoleApp1.SR1.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEruoToDH", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ConversionEruoToDHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public ConversionEruoToDHRequest() {
        }
        
        public ConversionEruoToDHRequest(double montant) {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEruoToDHResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ConversionEruoToDHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConversionEruoToDHResponse() {
        }
        
        public ConversionEruoToDHResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueServiceChannel : ConsoleApp1.SR1.BanqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueServiceClient : System.ServiceModel.ClientBase<ConsoleApp1.SR1.BanqueService>, ConsoleApp1.SR1.BanqueService {
        
        public BanqueServiceClient() {
        }
        
        public BanqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SR1.listCompteResponse ConsoleApp1.SR1.BanqueService.listCompte(ConsoleApp1.SR1.listCompteRequest request) {
            return base.Channel.listCompte(request);
        }
        
        public ConsoleApp1.SR1.compte[] listCompte() {
            ConsoleApp1.SR1.listCompteRequest inValue = new ConsoleApp1.SR1.listCompteRequest();
            ConsoleApp1.SR1.listCompteResponse retVal = ((ConsoleApp1.SR1.BanqueService)(this)).listCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SR1.listCompteResponse> ConsoleApp1.SR1.BanqueService.listCompteAsync(ConsoleApp1.SR1.listCompteRequest request) {
            return base.Channel.listCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SR1.listCompteResponse> listCompteAsync() {
            ConsoleApp1.SR1.listCompteRequest inValue = new ConsoleApp1.SR1.listCompteRequest();
            return ((ConsoleApp1.SR1.BanqueService)(this)).listCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SR1.getCompteResponse ConsoleApp1.SR1.BanqueService.getCompte(ConsoleApp1.SR1.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public ConsoleApp1.SR1.compte getCompte(long code) {
            ConsoleApp1.SR1.getCompteRequest inValue = new ConsoleApp1.SR1.getCompteRequest();
            inValue.code = code;
            ConsoleApp1.SR1.getCompteResponse retVal = ((ConsoleApp1.SR1.BanqueService)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SR1.getCompteResponse> ConsoleApp1.SR1.BanqueService.getCompteAsync(ConsoleApp1.SR1.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SR1.getCompteResponse> getCompteAsync(long code) {
            ConsoleApp1.SR1.getCompteRequest inValue = new ConsoleApp1.SR1.getCompteRequest();
            inValue.code = code;
            return ((ConsoleApp1.SR1.BanqueService)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SR1.ConversionEruoToDHResponse ConsoleApp1.SR1.BanqueService.ConversionEruoToDH(ConsoleApp1.SR1.ConversionEruoToDHRequest request) {
            return base.Channel.ConversionEruoToDH(request);
        }
        
        public double ConversionEruoToDH(double montant) {
            ConsoleApp1.SR1.ConversionEruoToDHRequest inValue = new ConsoleApp1.SR1.ConversionEruoToDHRequest();
            inValue.montant = montant;
            ConsoleApp1.SR1.ConversionEruoToDHResponse retVal = ((ConsoleApp1.SR1.BanqueService)(this)).ConversionEruoToDH(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SR1.ConversionEruoToDHResponse> ConsoleApp1.SR1.BanqueService.ConversionEruoToDHAsync(ConsoleApp1.SR1.ConversionEruoToDHRequest request) {
            return base.Channel.ConversionEruoToDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SR1.ConversionEruoToDHResponse> ConversionEruoToDHAsync(double montant) {
            ConsoleApp1.SR1.ConversionEruoToDHRequest inValue = new ConsoleApp1.SR1.ConversionEruoToDHRequest();
            inValue.montant = montant;
            return ((ConsoleApp1.SR1.BanqueService)(this)).ConversionEruoToDHAsync(inValue);
        }
    }
}
