
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param code
     * @return
     *     returns ws.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "ws.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "ws.GetCompteResponse")
    @Action(input = "http://ws/BanqueService/getCompteRequest", output = "http://ws/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        long code);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompte", targetNamespace = "http://ws/", className = "ws.ListCompte")
    @ResponseWrapper(localName = "listCompteResponse", targetNamespace = "http://ws/", className = "ws.ListCompteResponse")
    @Action(input = "http://ws/BanqueService/listCompteRequest", output = "http://ws/BanqueService/listCompteResponse")
    public List<Compte> listCompte();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEruoToDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEruoToDH", targetNamespace = "http://ws/", className = "ws.ConversionEruoToDH")
    @ResponseWrapper(localName = "ConversionEruoToDHResponse", targetNamespace = "http://ws/", className = "ws.ConversionEruoToDHResponse")
    @Action(input = "http://ws/BanqueService/ConversionEruoToDHRequest", output = "http://ws/BanqueService/ConversionEruoToDHResponse")
    public double conversionEruoToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
